version: '2'

services:
  #------------------------------------------------
  # Database
  #------------------------------------------------
  database:
    image: postgres:13-alpine
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  #------------------------------------------------
  # Message broker
  #------------------------------------------------
  message-broker:
    image: rabbitmq:3.9-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  #------------------------------------------------
  # Elk
  #------------------------------------------------
  elk:
    image: cali/elk
    build: ./docker/elk
    ports:
      - '5601:5601'
      - '9200:9200'
      - '5044:5044'
    volumes:
      - ./docker/elk/logstash-config:/etc/logstash/conf.d/input.conf
    depends_on:
      - message-broker

volumes:
  database-data:
