name: Dockerbuild command

on:
  repository_dispatch:
    types: [dockerbuild-command]

# To filter the comment with the pull request: khan/pull-request-comment-trigger
# To get the ref_head of the current pull request and checkout the code: xt0rted/pull-request-comment-branch

jobs:
  slash-command-comment:
    name: Update the issue information
    runs-on: [self-hosted, node-16]
    steps:
      - name: Create URL to the run output
        id: vars
        run:
          echo ::set-output
          name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
      - name: Edit comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository:
            ${{ github.event.client_payload.github.payload.repository.full_name
            }}
          comment-id:
            ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            ---
            Docker build command detected
            > [Command run output][1]

            [1]: ${{ steps.vars.outputs.run-url }}

  docker-apps:
    # If we got some change inside apps/** we execute this job
    if: |
      !failure()
    needs: [slash-command-comment]
    runs-on: [self-hosted, node-16]
    outputs:
      apps: ${{ steps.apps.outputs.result }}
    steps:
      # Checkout the source code
      - uses: actions/checkout@v2

      - name: Return formatted output
        uses: actions/github-script@v3
        id: apps
        with:
          script: |
            const fs = require('fs');
            const dirs = fs.readdirSync('./apps');
            const apps = [];
            for (const dir of dirs) {
              try {
                const files = fs.readdirSync(`./apps/${dir}`);
                if (files.includes('Dockerfile')) {
                  apps.push(dir);
                }
              } catch {}
            }
            return apps;

  docker-release:
    # If we got some change inside apps/** we execute this job
    if: |
      !failure() &&
      !contains(needs.docker-apps.outputs.apps, '[]')
    needs: [docker-apps]
    strategy:
      matrix:
        app: ${{ fromJSON(needs.docker-apps.outputs.apps) }}
        node: [16.x]
        os: [ubuntu-latest]
        scope: [tractr]
        repository: [tractr]
    name: docker release ${{ matrix.app }} (@${{ matrix.scope }})
    runs-on: ['${{ matrix.os }}']
    steps:
      # Checkout the source code
      - uses: actions/checkout@v2

      # Setup the node js env
      - name: use node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: ${{ secrets.NPM_REGISTRY_URL }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Get some cache to speed up docker build
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.app }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.app }}-

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.1.1
        with:
          path: ./apps/${{ matrix.app }}

      # Register some meta data to build docker
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}},value=v${{ steps.extract_version.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=v${{ steps.extract_version.outputs.version }}
          images:
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.PROJECT_CODE
            }}/${{ matrix.app }}

      # Setup QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # RSetup buildx
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      # Loggin to our docker registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ steps.login-ecr.outputs.registry }}

      # Build and push our docker images to the registry
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./apps/${{ matrix.app }}/Dockerfile
          secret-files: npmrc=${{ env.NPM_CONFIG_USERCONFIG }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          build-args: |
            app=${{ matrix.app }}
            NODE_AUTH_TOKEN=${{ secrets.NPM_TOKEN }}

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      # Change the cache for buildx
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  docker-success:
    needs: [docker-release]
    if: always() && !failure()

    runs-on: [self-hosted, node-16]
    steps:
      - name: Add success reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository:
            ${{ github.event.client_payload.github.payload.repository.full_name
            }}
          comment-id:
            ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray

  docker-failure:
    needs: [docker-release]
    if: always() && failure()

    runs-on: [self-hosted, node-16]
    steps:
      - name: Add failure reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository:
            ${{ github.event.client_payload.github.payload.repository.full_name
            }}
          comment-id:
            ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: -1
