name: Stack release and Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  npm-release:
    name: Release npm packages
    uses: ./.github/workflows/release-npm.yml
    with:
      botName: tractr-bot
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

  upload-codecov:
    name: Upload code coverage to Codecov
    uses: ./.github/workflows/test.yml
    with:
      codecov: true
      build: false
      lint: false
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
